[package]
name = "lfs"
version = "0.1.0"
authors = ["Mark https://github.com/riflechess"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exitcode = "1.1.2"
walkdir = "2"
