FROM php:7.4-apache

RUN apt-get update && \
    apt-get install -y vim net-tools procps curl iputils-ping  && \
    mkdir -p /opt/solr/af_dataset/ && \ 
    sed -i 's/# alias ll/alias ll/g' /root/.bashrc && \
    sed -i 's/# alias ls/alias ls/g' /root/.bashrc && \
    sed -i 's/# export LS_OPTIONS/export LS_OPTIONS/g' /root/.bashrc && \
    sed -i 's/# eval "`dircolors`"/eval "`dircolors`"/g' /root/.bashrc

COPY ./www/ /var/www/html/
COPY ./binary/lfs /usr/local/bin/

RUN mv /var/www/html/cs.conf /etc/apache2/sites-available/ && \
    chmod u+s /usr/local/bin/lfs && \
    sed -e 's/Options Indexes/Options /g' -i /etc/apache2/apache2.conf && \ 
    echo "ServerSignature Off" >> /etc/apache2/apache2.conf && \
    echo "ServerTokens Prod" >> /etc/apache2/apache2.conf  

RUN a2ensite cs && a2dissite 000-default

EXPOSE 80
