FROM php:7.4-apache

RUN apt-get update && \
    apt-get install -y vim net-tools procps curl iputils-ping  && \
    mkdir -p /opt/solr/af_dataset/ && \ 
    sed -i 's/# alias ll/alias ll/g' /root/.bashrc && \
    sed -i 's/# alias ls/alias ls/g' /root/.bashrc && \
    sed -i 's/# export LS_OPTIONS/export LS_OPTIONS/g' /root/.bashrc && \
    sed -i 's/# eval "`dircolors`"/eval "`dircolors`"/g' /root/.bashrc

COPY ./www/ /var/www/html/
COPY ./binary/lfs /usr/local/bin/

RUN chown -R www-data:www-data /var/www/html/ && \
    a2enmod ssl && \
    a2enmod rewrite && \
    mv /var/www/html/cs.conf /etc/apache2/sites-available/ && \
    chmod u+s /usr/local/bin/lfs 

RUN a2ensite cs && a2dissite 000-default

EXPOSE 80
